name: xpath
version: 0.0.1
authors:
- Peter Schonefeld <peter.schonefeld@gmail.com>
description: Dart implementation of Xpath 3
homepage: http://pschonefeld.github.io/xpath.dart/
environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  xml: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'

analyzer:
  strong-mode: true